#include "../include/common_data.h"

RPS_SERVER_IP[48] = {0,};	
RPS_SERVER_PORT = 6610;		
REDIS_CENTER_IP[48] = {0,};		
REDIS_STATUS_PORT = 5126;	
REDIS_AUTH_PORT = 5116;		
REDIS_RECONN_INTERNAL = 5;
REDIS_CHECKHEALTH_INTERNAL = 60;
HEATER_BEAT_INTERNAL = 120;	
HEART_BEAT_TIMEOUT = 240;		
REDIS_EXPIRE_TIME = 300;


