#include "../include/common_data.h"

char RPS_SERVER_IP[48] = {0,};	
int RPS_SERVER_PORT = 6610;		
char REDIS_CENTER_IP[48] = {0,};		
int REDIS_STATUS_PORT = 5126;	
int REDIS_AUTH_PORT = 5116;		
int REDIS_RECONN_INTERNAL = 5;
int REDIS_CHECKHEALTH_INTERNAL = 60;
int HEATER_BEAT_INTERNAL = 120;	
int HEART_BEAT_TIMEOUT = 240;		
int REDIS_EXPIRE_TIME = 300;	
